#! /bin/bash

# sed for libcurl configure.ac
curdir=`pwd`
# read to array
ac_config_file_line=`grep -n -A 1000000 "AC_CONFIG_FILES(" ${curdir}/curl/configure.ac | grep -B 1000000 'AC_OUTPUT' | sed -e "s/[:-].*//"`

# get config begin end end
begin=`echo ${ac_config_file_line} | awk -F' ' '{print $1}'`
end=`echo ${ac_config_file_line} | awk -F' ' '{print $NF}'`

# sed to libcurl configure.ac
sed -i "${begin},${end}d" ${curdir}/curl/configure.ac
begin=`expr ${begin} + 1`

sed -i "${begin}a AC_CONFIG_FILES([Makefile include/Makefile include/curl/Makefile src/Makefile lib/Makefile lib/libcurl.vers curl-config libcurl.pc])\\
AC_OUTPUT" ${curdir}/curl/configure.ac

# sed to libcurl Makefile.am
sed -i 's/^DIST_SUBDIRS/\#DIST_SUBDIRS/g' ${curdir}/curl/Makefile.am
sed -i 's/^	cd docs && $(MAKE) install/\#	cd docs && $(MAKE) install/g' ${curdir}/curl/Makefile.am

# exec autoreconf
exec autoreconf -vi -I `pwd`/m4