/* JaneClone - a text board site viewer for 2ch
 * Copyright (C) 2012 Hiroyuki Nagata
 *
 * This program is free software; you can redistribute it and/or
 * modify it under the terms of the GNU General Public License
 * as published by the Free Software Foundation; either version 2
 * of the License, or (at your option) any later version.

 * This program is distributed in the hope that it will be useful,
 * but WITHOUT ANY WARRANTY; without even the implied warranty of
 * MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
 * GNU General Public License for more details.

 * You should have received a copy of the GNU General Public License
 * along with this program; if not, write to the Free Software
 * Foundation, Inc., 59 Temple Place - Suite 330, Boston, MA  02111-1307, USA.
 *
 * Contributor:
 *	Hiroyuki Nagata <newserver002@gmail.com>
 */

// -*- C++ -*- generated by wxGlade 0.6.3 on Tue Nov 01 01:42:24 2011

#ifndef JANECLONE_H
#define JANECLONE_H

// 純粋なwxWidgetsライブラリはここに
#include <wx/wx.h>
#include <wx/image.h>
#include <wx/statusbr.h>
#include <wx/splitter.h>
#include <wx/treectrl.h>
#include <wx/msgdlg.h>
#include <wx/imaglist.h>
#include <wx/artprov.h>
#include <wx/xml/xml.h>
#include <wx/txtstrm.h>
#include <wx/wfstream.h>
#include <wx/string.h>
#include <wx/file.h>
#include <wx/aui/aui.h>
#include <wx/aui/auibook.h>
#include <wx/dialog.h>
#include <wx/event.h>
#include <wx/wfstream.h>
#include <wx/filesys.h>
#include <wx/filename.h>
#include <wx/filefn.h>
#include <wx/mstream.h>
#include <wx/url.h>
#include <wx/protocol/http.h>
#include <wx/datstrm.h>
#include <wx/aboutdlg.h>
#include <wx/hashmap.h>
#include <wx/regex.h>
#include <wx/dir.h>
#include <wx/listctrl.h>
#include <wx/sizer.h>
#include <wx/textfile.h>
#include <wx/convauto.h>
#include <wx/process.h>
#include <wx/srchctrl.h>
#include <wx/richtext/richtextctrl.h>

// 自作クラスのヘッダ
#include "ExtractBoardList.h"
#include "SocketCommunication.h"
#include "DataType.h"
#include "MetakitAccessor.h"
#include "JaneCloneUtil.h"

// 名前空間
using namespace std;

/*
 * 定数値の宣言
 */

// 板一覧情報ファイルのパス
static const wxString BOARD_LIST_PATH = wxT("./dat/boardlist.html");
// 板一覧情報ファイルのヘッダ情報のパス
static const wxString BOARD_LIST_HEADER_PATH = wxT("./dat/boardlistheader.html");

class JaneClone : public wxFrame {

public:
  // begin wxGlade: JaneClone::ids
  // end wxGlade

  JaneClone(wxWindow* parent, int id, const wxString& title, const wxPoint& pos=wxDefaultPosition, const wxSize& size=wxDefaultSize, long style=wxDEFAULT_FRAME_STYLE);
  ~JaneClone();

  // 板名とそのURLを保持するwxHashMap　JaneCloneが起動している間は保持される
  // URLvsBoardNameクラスについてはDataType.h参照
  WX_DECLARE_HASH_MAP( int, URLvsBoardName*, wxIntegerHash, wxIntegerEqual, NameURLHash );
  // HashMapの本体
  NameURLHash retainHash;

private:
  // begin wxGlade: JaneClone::methods
  // イベントテーブル系
  void OnQuit(wxCommandEvent& event);
  void OnAbout(wxCommandEvent& event);
  void OnGetBoardList(wxCommandEvent& event);
  void OnVersionInfo(wxCommandEvent& event);
  void OnContext(wxContextMenuEvent& event);
  void OnRightClick(wxAuiNotebookEvent& event);
  void OnCloseWindow(wxCloseEvent& event);

  // 各種GUI上の設定
  void SetJaneCloneManuBar();
  void SetProperties();
  void DoLayout();
  void SetJaneCloneAuiPaneInfo();

  // 取得した板一覧ファイルからデータを抽出してレイアウトに反映するメソッド
  void SetBoardList();

  // すべてのウィジェットが載るAuiマネージャー
  wxAuiManager m_mgr;
  // ステータスバー表示用文字列
  wxStatusBar* 	statusBarStr;

  /**
   * 画面上部のオブジェクトとメソッド
   */
  // 検索バー
  wxSearchCtrl* m_search_ctrl;
  // URL入力欄が載るパネル
  wxPanel* m_url_input_panel;
  // URL入力欄
  wxTextCtrl* m_url_input;
  // URL入力欄の画像つきボタン
  wxBitmapButton* m_url_input_button;
  // URLを表すString
  wxString m_url_text;

  /**
   * 画面左側のオブジェクトとメソッド
   */
  // ツリーコントロールは内部からならいじれるようにしておく
  wxTreeCtrl* 	m_tree_ctrl;
  wxTreeItemData*	m_treeData;
  wxTreeItemId 	m_rootId;

  //　ツリーコントロールにクリックした時のイベント
  void OnGetBoardInfo(wxTreeEvent& event);

  /**
   * 右上のオブジェクトとメソッド
   */
  // 右側上部・板一覧のノートブックとスレッド一覧リストが載るウィンドウ
  wxWindow* boardListThreadList;
  // wxNotebook（上部）が乗るサイザー
  wxBoxSizer* topNote;
  // 板名のツリーコントロールをクリックした場合表示されるwxNoteBook
  wxAuiNotebook* boardNoteBook;
  // 板一覧のツリーをクリックして、それをノートブックに反映するメソッド
  void SetBoardNameToNoteBook(wxString& boardName, wxString& boardURL, wxString& boardNameAscii);

  /**
   * 右下のオブジェクトとメソッド
   */
  // 右側下部・スレッド一覧のノートブックとスレの中身が載るウィンドウ
  wxWindow* threadTabThreadContent;
  // wxNotebook（下部）が乗るサイザー
  wxBoxSizer* bottomNote;
  // 板名のツリーコントロールをクリックした場合表示されるwxNoteBook
  wxAuiNotebook* threadNoteBook;
  // スレッド一覧をクリックすると、それをスレ表示画面に反映するメソッド（スタブ）
  void SetThreadContentToNoteBook();

  /**
   * その他のオブジェクトとメソッド
   */
  // スレッド一覧の情報を保持するwxHashMap　ユーザが板名をクリックするたびに作られる
  // ThreadListクラスについてはDataType.h参照
  WX_DECLARE_HASH_MAP( int, ThreadList*, wxIntegerHash, wxIntegerEqual, ThreadListHash );
  // ThreadListHashの本体
  ThreadListHash threadListHash;

  // スレッド一覧のハッシュマップを作成するメソッド
  void SetThreadList(wxString& inputThreadListdat);

  DECLARE_EVENT_TABLE()
}; // wxGlade: end class

#endif // JANECLONE_H
