// -*- C++ -*- generated by wxGlade 0.6.3 on Tue Nov 01 01:42:24 2011

#ifndef JANECLONE_H
#define JANECLONE_H

// 純粋なwxWidgetsライブラリはここに
#include <wx/wx.h>
#include <wx/image.h>
#include <wx/statusbr.h>
#include <wx/splitter.h>
#include <wx/treectrl.h>
#include <wx/msgdlg.h>
#include <wx/imaglist.h>
#include <wx/artprov.h>
#include <wx/xml/xml.h>x
#include <wx/txtstrm.h>
#include <wx/wfstream.h>
#include <wx/string.h>
#include <wx/file.h>
#include <wx/aui/auibook.h>
#include <wx/dialog.h>
#include <wx/event.h>
#include <wx/wfstream.h>
#include <wx/filesys.h>
#include <wx/filename.h>
#include <wx/filefn.h>
#include <wx/mstream.h>
#include <wx/url.h>
#include <wx/protocol/http.h>
#include <wx/datstrm.h>
#include <wx/aboutdlg.h>
#include <wx/hashmap.h>
#include <wx/regex.h>
#include <wx/dir.h>
#include <wx/listctrl.h>
#include <wx/sizer.h>
#include <wx/textfile.h>
#include <wx/convauto.h>
#include <wx/process.h>

// 自作クラスのヘッダ
#include "ExtractBoardList.h"
#include "SocketCommunication.h"
#include "DataType.h"
#include "SQLiteAccessor.h"
#include "JaneCloneUtil.h"

// 名前空間
using namespace std;

// テキストの終端文字が何で終わるのかを定義
#if defined(__WXMSW__)
	#define TextEndLineType wxTextFileType_Dos
#endif
#if defined(__WXGTK__)
	#define TextEndLineType	wxTextFileType_Unix
#endif
#if defined(__WXMAC__)
	#define TextEndLineType wxTextFileType_Mac
#endif

/*
 * 定数値の宣言
 */

// 板一覧情報ファイルのパス
static const wxString BOARD_LIST_PATH = wxT("./dat/boardlist.html");
// 板一覧情報ファイルのヘッダ情報のパス
static const wxString BOARD_LIST_HEADER_PATH = wxT("./dat/boardlistheader.html");

class JaneClone : public wxFrame {

public:
  // begin wxGlade: JaneClone::ids
  // end wxGlade

  JaneClone(wxWindow* parent, int id, const wxString& title, const wxPoint& pos=wxDefaultPosition, const wxSize& size=wxDefaultSize, long style=wxDEFAULT_FRAME_STYLE);

  // 板名とそのURLを保持するwxHashMap　JaneCloneが起動している間は保持される
  // URLvsBoardNameクラスについてはDataType.h参照
  WX_DECLARE_HASH_MAP( int, URLvsBoardName*, wxIntegerHash, wxIntegerEqual, NameURLHash );
  // HashMapの本体
  NameURLHash retainHash;

private:
  // begin wxGlade: JaneClone::methods
  // イベントテーブル系
  void OnQuit(wxCommandEvent& event);
  void OnAbout(wxCommandEvent& event);
  void OnGetBoardList(wxCommandEvent& event);
  void OnVersionInfo(wxCommandEvent& event);
  void OnContext(wxContextMenuEvent& event);
  void OnRightClick(wxAuiNotebookEvent& event);
  void OnCloseWindow(wxCloseEvent& event);

  void SetProperties();
  void DoLayout();

  // 取得した板一覧ファイルからデータを抽出してレイアウトに反映するメソッド
  void SetBoardList();

protected:
  // URL入力欄のテキスト操作用
  wxTextCtrl* 	textCtlForURL;
  // ステータスバー表示用文字列
  wxStatusBar* 	statusBarStr;
  // ツリーコントロールは内部からならいじれるようにしておく
  wxTreeCtrl* 	m_tree_ctrl;
  wxTreeItemData*	m_treeData;
  wxTreeItemId 	m_rootId;
  wxStaticText* 	label_1;
  wxButton* 		button_1;

  // 左側
  wxSplitterWindow* window_1;
  // 右側
  wxSplitterWindow* window_2;

  // 左側　-- 板一覧がツリーコントロールに入る
  wxPanel* window_1_pane_1;
  // 左側 -- 未使用　デバッグ画面でもつけるか
  wxPanel* window_1_pane_2;

  // 右側上段 -- 板一覧
  wxPanel* window_2_pane_1;
  // 右側下段　-- 個別のスレ
  wxPanel* window_2_pane_2;

  //　ツリーコントロールにクリックした時のイベント
  void OnGetBoardInfo(wxTreeEvent& event);

  // wxNotebook（上部）が乗るサイザー
  wxBoxSizer* topNote;
  /** 板名のツリーコントロールをクリックした場合表示されるwxNoteBook　*/
  wxAuiNotebook* boardNoteBook;

  // 板一覧のツリーをクリックして、それをノートブックに反映するメソッド
  void SetBoardNameToNoteBook(wxString& boardName, wxString& boardURL, wxString& boardNameAscii);

  // スレッド一覧の情報を保持するwxHashMap　ユーザが板名をクリックするたびに作られる
  // ThreadListクラスについてはDataType.h参照
  WX_DECLARE_HASH_MAP( int, ThreadList*, wxIntegerHash, wxIntegerEqual, ThreadListHash );
  // ThreadListHashの本体
  ThreadListHash threadListHash;

  // スレッド一覧のハッシュマップを作成するメソッド
  void SetThreadList(wxString& inputThreadListdat);

  DECLARE_EVENT_TABLE()
}; // wxGlade: end class

#endif // JANECLONE_H
