// -*- C++ -*- generated by wxGlade 0.6.5 on Wed May 22 03:50:59 2013

#ifndef OTHERPANELS_HPP
#define OTHERPANELS_HPP

#include <wx/wx.h>
#include <wx/image.h>
#include <wx/spinctrl.h>
#include <wx/filepicker.h>
#include "enums.hpp"
#include "janecloneutil.hpp"

// begin wxGlade: ::extracode
// end wxGlade

/**
 * 各種ネットワーク設定用画面
 */
class NetworkSettingPanel: public wxPanel {
public:
     // begin wxGlade: NetworkSettingPanel::ids
     // end wxGlade
     NetworkSettingPanel(wxWindow* parent, const wxPoint& pos=wxDefaultPosition, const wxSize& size=wxDefaultSize, long style=0);

private:
     // begin wxGlade: NetworkSettingPanel::methods
     void set_properties();
     void do_layout();
     // end wxGlade

protected:
     // begin wxGlade: NetworkSettingPanel::attributes
     wxCheckBox* proxyUseCheck;
     wxCheckBox* proxyCacheUseCheck;
     wxPanel* panel_6;
     wxStaticText* label_6;
     wxStaticText* label_7;
     wxStaticText* label_8;
     wxTextCtrl* recProxyAddrTC;
     wxTextCtrl* recProxyPortTC;
     wxStaticText* label_9;
     wxTextCtrl* sedProxyAddrTC;
     wxTextCtrl* sedProxyPortTC;
     wxStaticText* label_10;
     wxTextCtrl* authSSLAddrTC;
     wxTextCtrl* authSSLPortTC;
     wxStaticText* label_11;
     wxStaticText* label_12;
     wxTextCtrl* basicAuthUserNameTC;
     wxPanel* panel_8;
     wxStaticText* label_13;
     wxTextCtrl* basicAuthPasswordTC;
     wxPanel* panel_9;
     wxPanel* panel_7;
     wxPanel* panel_1;
     wxStaticText* label_4;
     wxTextCtrl* receiveTimeoutTC;
     wxPanel* panel_2;
     wxStaticText* label_5;
     wxTextCtrl* connectTimeoutTC;
     wxPanel* panel_3;
     wxStaticText* label_3;
     wxTextCtrl* boardListURLTC;
     wxPanel* panel_4;
     wxStaticText* label_1;
     wxTextCtrl* receiveBufferSizeTC;
     wxStaticText* label_2;
     wxSpinCtrl* maxConnSC;
     wxPanel* panel_5;
     // end wxGlade
}; // wxGlade: end class

/**
 * 各種パス設定用画面
 */
class PathSettingPanel: public wxPanel {
public:
     // begin wxGlade: PathSettingPanel::ids
     // end wxGlade
     PathSettingPanel(wxWindow* parent, const wxPoint& pos=wxDefaultPosition, const wxSize& size=wxDefaultSize, long style=0);

private:
     // begin wxGlade: PathSettingPanel::methods
     void set_properties();
     void do_layout();
     // end wxGlade
     void OnBrowserCheck(wxCommandEvent& event) {
	  // デフォルトのブラウザを指定する
	  JaneCloneUtil::SetJaneCloneProperties<bool>(wxT("SPECIFY_DEFAULT_BROWSER"), browserCheck->IsChecked());
	  this->set_properties();
     };
     void OnChangeDirPickerBrowser(wxFileDirPickerEvent& event) {
	  // ブラウザのパスを更新する
	  JaneCloneUtil::SetJaneCloneProperties<wxString>(wxT("DEFAULT_BROWSER_PATH"), event.GetPath());
	  this->set_properties();
     };
     void OnChangeDirPickerBoardList(wxFileDirPickerEvent& event) {
	  // 板一覧のパスを更新する
	  JaneCloneUtil::SetJaneCloneProperties<wxString>(wxT("DEFAULT_BOARDLIST_PATH"), event.GetPath());
	  this->set_properties();
     };
     void OnChangeDirPickerSkin(wxFileDirPickerEvent& event) {
	  // スキンのパスを更新する
	  JaneCloneUtil::SetJaneCloneProperties<wxString>(wxT("DEFAULT_SKINFILE_PATH"), event.GetPath());
	  this->set_properties();
     };

protected:
     // begin wxGlade: PathSettingPanel::attributes
     wxCheckBox* browserCheck;
     wxStaticText* label_1;
     wxTextCtrl* browserPathTC;
     wxDirPickerCtrl* dirPicker1;
     wxStaticText* label_2;
     wxTextCtrl* boardListTC;
     wxDirPickerCtrl* dirPicker2;
     wxStaticText* label_3;
     wxTextCtrl* skinPathTC;
     wxDirPickerCtrl* dirPicker3;
     // end wxGlade
     DECLARE_EVENT_TABLE() 
}; // wxGlade: end class

// begin wxGlade: ::extracode
// end wxGlade

/**
 * 各種動作設定用画面
 */
class BehaviorPanel: public wxPanel {
public:
    // begin wxGlade: BehaviorPanel::ids
    // end wxGlade

    BehaviorPanel(wxWindow* parent, const wxPoint& pos=wxDefaultPosition, const wxSize& size=wxDefaultSize, long style=0);

private:
    // begin wxGlade: BehaviorPanel::methods
    void set_properties();
    void do_layout();
    // end wxGlade

protected:
    // begin wxGlade: BehaviorPanel::attributes
    wxStaticBox* sizer_7_staticbox;
    wxStaticBox* sizer_5_staticbox;
    wxStaticBox* sizer_3_staticbox;
    wxStaticBox* sizer_2_staticbox;
    wxCheckBox* openBNewTabCheck;
    wxCheckBox* onlyOneCategoryCheck;
    wxPanel* panel_2;
    wxCheckBox* openTNewTabCheck;
    wxComboBox* threadNewTabCombo;
    wxPanel* panel_6;
    wxCheckBox* lastReadThreadPosCheck;
    wxPanel* panel_3;
    wxRadioBox* threadJumpSettingRadio;
    wxCheckBox* redrawNewThreadCheck;
    wxStaticText* label_1;
    wxComboBox* showResponseCombo;
    wxPanel* panel_7;
    wxPanel* panel_4;
    wxCheckBox* favoriteNewTabCheck;
    wxCheckBox* favoriteOnlyOneFolderCheck;
    wxPanel* panel_5;
    // end wxGlade
}; // wxGlade: end class

#endif // OTHERPANELS_H
