/* JaneClone - a text board site viewer for 2ch
 * Copyright (C) 2012 Hiroyuki Nagata
 *
 * This program is free software; you can redistribute it and/or
 * modify it under the terms of the GNU General Public License
 * as published by the Free Software Foundation; either version 2
 * of the License, or (at your option) any later version.

 * This program is distributed in the hope that it will be useful,
 * but WITHOUT ANY WARRANTY; without even the implied warranty of
 * MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
 * GNU General Public License for more details.

 * You should have received a copy of the GNU General Public License
 * along with this program; if not, write to the Free Software
 * Foundation, Inc., 59 Temple Place - Suite 330, Boston, MA  02111-1307, USA.
 *
 * Contributor:
 *	Hiroyuki Nagata <newserver002@gmail.com>
 */

// -*- C++ -*- generated by wxGlade 0.6.5 on Tue May 21 00:18:19 2013

#include "settingwindow.hpp"

// begin wxGlade: ::extracode
// end wxGlade

BEGIN_EVENT_TABLE(SettingDialog, wxDialog)
   EVT_BUTTON(ID_OnOkSetting, SettingDialog::OnQuit)
   EVT_BUTTON(ID_OnCancelSetting, SettingDialog::OnQuit)
END_EVENT_TABLE()

/**
 * 設定画面のコンストラクタ
 */
SettingDialog::SettingDialog(wxWindow* parent, int id, const wxString& title, const wxPoint& pos, const wxSize& size, long style):
     wxDialog(parent, id, title, pos, size, wxDEFAULT_DIALOG_STYLE) {

     // begin wxGlade: SettingDialog::SettingDialog
     bottomPanel = new wxPanel(this, wxID_ANY);
     window_1 = new wxSplitterWindow(this, wxID_ANY, wxDefaultPosition, wxDefaultSize, wxSP_3D|wxSP_BORDER);
     // 左側のツリー部分
     treePanel = new wxPanel(window_1, wxID_ANY);
     settingTreeCtrl = new wxTreeCtrl(treePanel, wxID_ANY, wxDefaultPosition, wxDefaultSize, 
				      wxTR_HIDE_ROOT|wxTR_HAS_BUTTONS|wxTR_DEFAULT_STYLE|wxSUNKEN_BORDER);
     // 右側の設定画面部分
     settingPanel = new wxPanel(window_1, wxID_ANY);

     spacePanel = new wxPanel(bottomPanel, wxID_ANY);
     // OK,キャンセルボタン
     okButton = new wxButton(bottomPanel, ID_OnOkSetting, wxT("OK"));
     cancelButton = new wxButton(bottomPanel, ID_OnCancelSetting, wxT("キャンセル"));

     SetProperties();
     DoLayout();
     // end wxGlade
}
/**
 * ウィンドウのプロパティを設定
 */
void SettingDialog::SetProperties() {
     // begin wxGlade: SettingDialog::set_properties
     SetTitle(wxT("設定 - "));
     SetSize(wxSize(960, 640));

     // ツリーコントロールの表示内容を設定する
     settingTreeCtrl->AddRoot(wxEmptyString);
     wxTreeItemId item = settingTreeCtrl->AppendItem(settingTreeCtrl->GetRootItem(), wxT("基本"));
     settingTreeCtrl->AppendItem(item, wxT("通信"));
     settingTreeCtrl->AppendItem(item, wxT("パス"));
     settingTreeCtrl->AppendItem(item, wxT("動作"));
     settingTreeCtrl->AppendItem(item, wxT("操作"));
     settingTreeCtrl->AppendItem(item, wxT("タブ操作"));
     settingTreeCtrl->AppendItem(item, wxT("書き込み"));
     settingTreeCtrl->AppendItem(item, wxT("Doe"));
     settingTreeCtrl->AppendItem(item, wxT("その他１"));
     settingTreeCtrl->AppendItem(item, wxT("User"));
     item = settingTreeCtrl->AppendItem(settingTreeCtrl->GetRootItem(), wxT("機能"));
     settingTreeCtrl->AppendItem(item, wxT("ヒント"));
     settingTreeCtrl->AppendItem(item, wxT("あぼーん"));
     settingTreeCtrl->AppendItem(item, wxT("コマンド"));
     settingTreeCtrl->AppendItem(item, wxT("マウス"));
     settingTreeCtrl->AppendItem(item, wxT("検索・更新"));
     settingTreeCtrl->AppendItem(item, wxT("スレッド"));
     settingTreeCtrl->AppendItem(item, wxT("画像"));
     settingTreeCtrl->AppendItem(item, wxT("その他２"));
     item = settingTreeCtrl->AppendItem(settingTreeCtrl->GetRootItem(), wxT("外観"));
     settingTreeCtrl->AppendItem(item, wxT("スレ覧項目"));
     settingTreeCtrl->AppendItem(item, wxT("タブ"));
     settingTreeCtrl->AppendItem(item, wxT("スタイル"));
     settingTreeCtrl->AppendItem(item, wxT("色・フォント"));
     settingTreeCtrl->AppendItem(item, wxT("タブ色"));
     settingTreeCtrl->ExpandAll();
     // end wxGlade
}
/**
 * レイアウトの設定
 */
void SettingDialog::DoLayout() {
     // begin wxGlade: SettingDialog::do_layout
     wxBoxSizer* vbox = new wxBoxSizer(wxVERTICAL);
     wxBoxSizer* bottomSizer = new wxBoxSizer(wxHORIZONTAL);
     wxBoxSizer* treeVbox = new wxBoxSizer(wxVERTICAL);
     treeVbox->Add(settingTreeCtrl, 1, wxEXPAND, 0);
     treePanel->SetSizer(treeVbox);
     window_1->SplitVertically(treePanel, settingPanel);
     vbox->Add(window_1, 1, wxEXPAND, 0);
     bottomSizer->Add(spacePanel, 1, wxEXPAND, 0);
     bottomSizer->Add(okButton, 0, 0, 5);
     bottomSizer->Add(cancelButton, 0, 0, 5);
     bottomPanel->SetSizer(bottomSizer);
     vbox->Add(bottomPanel, 0, wxTOP|wxEXPAND, 0);
     SetSizer(vbox);
     Layout();
     // end wxGlade
}
/**
 * 設定画面のクローズ
 */
void SettingDialog::OnQuit(wxCommandEvent& event) {
     this->Destroy();
}
