/* JaneClone - a text board site viewer for 2ch
 * Copyright (C) 2012 Hiroyuki Nagata
 *
 * This program is free software; you can redistribute it and/or
 * modify it under the terms of the GNU General Public License
 * as published by the Free Software Foundation; either version 2
 * of the License, or (at your option) any later version.

 * This program is distributed in the hope that it will be useful,
 * but WITHOUT ANY WARRANTY; without even the implied warranty of
 * MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
 * GNU General Public License for more details.

 * You should have received a copy of the GNU General Public License
 * along with this program; if not, write to the Free Software
 * Foundation, Inc., 59 Temple Place - Suite 330, Boston, MA  02111-1307, USA.
 *
 * Contributor:
 *	Hiroyuki Nagata <newserver002@gmail.com>
 */

// -*- C++ -*- generated by wxGlade 0.6.3 on Sat Dec 29 22:07:54 2012

#include <wx/wx.h>
#include <wx/image.h>

#ifndef THREADCONTENTBAR_H
#define THREADCONTENTBAR_H

// begin wxGlade: ::dependencies
// end wxGlade

// begin wxGlade: ::extracode

// end wxGlade


class ThreadContentBar: public wxWindow {
public:
    // begin wxGlade: ThreadContentBar::ids
    // end wxGlade

    ThreadContentBar(wxWindow* parent, int id, const wxString& title, const wxPoint& pos=wxDefaultPosition, const wxSize& size=wxDefaultSize, long style=wxDEFAULT_FRAME_STYLE);

private:
    // begin wxGlade: ThreadContentBar::methods
    void set_properties();
    void do_layout();
    // end wxGlade

protected:
    // begin wxGlade: ThreadContentBar::attributes
    wxStaticText* threadName;
    wxPanel* spacePanel1;
    wxBitmapButton* autoReloadButton;
    wxBitmapButton* redResExtractButton;
    wxBitmapButton* refleshButton;
    wxBitmapButton* scrollToNewResponseButton;
    wxBitmapButton* stopButton;
    wxBitmapButton* resExtractButton;
    wxBitmapButton* newThreadButton;
    wxBitmapButton* responseButton;
    wxBitmapButton* bookMarkButton;
    wxBitmapButton* deleteLogButton;
    wxBitmapButton* closeButton;
    wxPanel* threadContentsBarUpperSizer;
    wxBitmapButton* nomalSearchButton;
    wxComboBox* searchWordCombo;
    wxButton* backwordButton;
    wxButton* forwardButton;
    wxPanel* panel_2;
    wxBitmapButton* hideSearchBarButton;
    wxPanel* panel_1;
    // end wxGlade
}; // wxGlade: end class


#endif // THREADCONTENTBAR_H
