name: Create package of JaneClone

on:
  push:
    branches:
    - releases/*

env:
  ACTIONS_ALLOW_UNSECURE_COMMANDS: true

jobs:
  build:
    runs-on: ubuntu-latest # focal

    steps:
    - name: Checkout source
      uses: actions/checkout@v2

    - name: install-cmake
      uses: Symbitic/install-cmake@v0.1.0
      with:
        cmake: 3.17.2
        ninja: 1.9.0

    - name: Update packages
      run: sudo apt-get update -y

    - name: Install build tools
      run: sudo apt-get install -y libwxbase3.0-dev libwxgtk3.0-gtk3-dev libwxsqlite3-3.0-dev libxml2-dev libcurl4-openssl-dev libssl-dev

    - name: Configure CMake
      run: cmake -B ${{github.workspace}}/build -G Ninja

    - name: Build
      working-directory: ${{github.workspace}}/build
      run: ninja && ninja package

    - name: Publish .deb to Gemfury
      env:
        GEMFURY_PUSH_TOKEN: ${{ secrets.GEMFURY_PUSH_TOKEN }}
      run: |
        curl -F package=@build/janeclone_*_*.deb https://${GEMFURY_PUSH_TOKEN}@push.fury.io/hangingman/
